export const ActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAILURE: 'LOGIN_REQUEST_FAILURE',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_REQUEST_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_REQUEST_FAILURE: 'SIGN_UP_REQUEST_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  FIREBASE_AUTH_ACTIVE: 'FIREBASE_AUTH_ACTIVE',
  FIREBASE_AUTH_INACTIVE: 'FIREBASE_AUTH_INACTIVE',
  SET_ACTIVE_USER_TITLE: 'SET_ACTIVE_USER_TITLE',
  PASSWORD_RESET_REQUEST_LOADING: 'PASSWORD_RESET_REQUEST_LOADING',
  PASSWORD_RESET_REQUEST_SUCCESS: 'PASSWORD_RESET_REQUEST_SUCCESS',
  PASSWORD_RESET_REQUEST_FAILURE: 'PASSWORD_RESET_REQUEST_FAILURE',

  TRACK_CHANGED: 'TRACK_CHANGED',
  TRACK_PLAYER_STATE_CHANGED: 'TRACK_PLAYER_STATE_CHANGED',
};
